version: '3.9'
services:
  #jupyter
  jupyter:
    hostname: jupyter_container
    container_name: jupyter_container
    build:
      #path to docker files folder
      context: ../docker_files/jupyter
      #docker file name for jupyter in docker files folder
      dockerfile: dockerfile_jupyter
    volumes:
      #path to file share
      - ../file_share/jupyter_data/:/home/jovyan/
    ports:
      - '8888:8888'
    networks:
      - postgres

  #postgresSQL BD
  postgres:
    hostname: postgres_container
    container_name: postgres_container
    build:
      #path to docker files folder
      context: ../docker_files/postgresql
      #docker file name for postgresql in docker files folder
      dockerfile: dockerfile_postgresql
    volumes:
      #path to file share
      - ../file_share/postgresql_data/:/var/lib/postgresql/data
    #set the DB name, user and password
    environment:
      POSTGRES_DB: 'postgres_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
        - '5432:5432'
    networks:
      - postgres

  #pgadmin
  pgadmin:
    hostname: pgadmin_container
    container_name: pgadmin_container
    build:
      #path to docker files folder
      context: ../docker_files/pgadmin
      #docker file name for pgadmin in docker files folder
      dockerfile: dockerfile_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@default.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpswrd"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    #path to file share
    volumes:
      - ../file_share/pgadmin_data/:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge