version: '3.9'
services:
  jupyter:
    build:
      #path to docker files folder
      context: ../dockerfile
      #docker file name for jupyter in docker files folder
      dockerfile: dockerfile_jupyter
    volumes:
      #path to file share
      - ../file_share/jupyter/:/home/jovyan/
    ports:
      - "8888:8888"
